######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 25 03:18:00 2008
######################################################################

TEMPLATE = app
QT -= gui
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
SOURCES += WikipediaAdapter.cpp
