######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 25 03:18:00 2008
######################################################################

TEMPLATE = app
QT -= gui
QT += sql xml
DEPENDPATH += .
INCLUDEPATH += .
SOURCES += MediawikiImporter.cpp
